# Generated by Django 4.2.6 on 2023-10-13 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advantage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('subtitle', models.CharField(max_length=100, verbose_name='Подзаголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='2023/10/13', verbose_name='Заголовок')),
            ],
            options={
                'verbose_name': 'Преимущества для главной страницы',
                'verbose_name_plural': 'Преимущества для главной страницы',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('images', models.ImageField(blank=True, default='', null=True, upload_to='', verbose_name='Иконка категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('key', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='2023/10/13')),
            ],
            options={
                'verbose_name': 'Картинка',
                'verbose_name_plural': 'Картинки',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Материал',
                'verbose_name_plural': 'Материалы',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('subtitle', models.CharField(max_length=200, verbose_name='Вид')),
                ('meta_description', models.TextField(blank=True, null=True, verbose_name='SEO описание')),
                ('meta_keywords', models.CharField(blank=True, max_length=255, null=True, verbose_name='SEO ключеве слова')),
                ('manufacturer', models.CharField(blank=True, max_length=100, verbose_name='Производитель')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='Страна')),
                ('delivery_days', models.IntegerField(default=0, verbose_name='Доставка в днях')),
                ('warranty', models.CharField(blank=True, max_length=100, verbose_name='гарантия')),
                ('price', models.IntegerField(blank=True, default=False, verbose_name='Цена')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликован')),
                ('is_top_product', models.BooleanField(default=False, verbose_name='Популярный')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icistore.category', verbose_name='Категория')),
                ('filters', models.ManyToManyField(blank=True, to='icistore.filter')),
                ('images', models.ManyToManyField(blank=True, to='icistore.imagemodel', verbose_name='Фото')),
                ('materials', models.ManyToManyField(blank=True, to='icistore.material', verbose_name='Материал ткани')),
            ],
        ),
        migrations.CreateModel(
            name='Chair',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='icistore.product')),
                ('appearance', models.CharField(choices=[('с высокой спинкой', 'С высокой спинкой'), ('с невысокой спинкой', 'С невысокой спинкой')], max_length=50, verbose_name='Спинка')),
                ('form', models.CharField(choices=[('круглая', 'Круглая'), ('прямоугольная', 'Прямоугольная')], max_length=50, verbose_name='Форма')),
                ('legs', models.CharField(choices=[('металл', 'Металл'), ('бук', 'Бук')], max_length=50, verbose_name='Материал')),
            ],
            options={
                'verbose_name': 'Кресло',
                'verbose_name_plural': 'Кресла',
            },
            bases=('icistore.product',),
        ),
        migrations.CreateModel(
            name='InteriorSofa',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='icistore.product')),
                ('appearance', models.CharField(choices=[('с высокой спинкой', 'С высокой спинкой'), ('с невысокой спинкой', 'С невысокой спинкой')], max_length=50, verbose_name='Спинка')),
                ('legs', models.CharField(choices=[('металл', 'Металл'), ('бук', 'Бук')], max_length=50, verbose_name='Материал')),
                ('has_armrests', models.BooleanField(default=False, verbose_name='Спальное место')),
            ],
            options={
                'verbose_name': 'Интерьерный диван',
                'verbose_name_plural': 'Интерьерные диваны',
            },
            bases=('icistore.product',),
        ),
        migrations.CreateModel(
            name='Ottoman',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='icistore.product')),
                ('form', models.CharField(choices=[('круглая', 'Круглая'), ('прямоугольная', 'Прямоугольная')], max_length=50, verbose_name='Форма')),
                ('legs', models.CharField(choices=[('металл', 'Металл'), ('бук', 'Бук')], max_length=50, verbose_name='Материал')),
            ],
            options={
                'verbose_name': 'Пуф',
                'verbose_name_plural': 'Пуфы',
            },
            bases=('icistore.product',),
        ),
        migrations.CreateModel(
            name='Sofa',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='icistore.product')),
                ('form', models.CharField(choices=[('эркерный', 'Эркерный'), ('модульный', 'Модульный'), ('прямой', 'Прямой'), ('угловой', 'Угловой')], max_length=50, verbose_name='Форма')),
                ('size', models.CharField(choices=[('до 2000мм', 'До 2000мм'), ('2000-3000мм', '2000-3000мм'), ('свыше 3000мм', 'Свыше 3000мм')], max_length=50, verbose_name='Размер')),
                ('has_sleeper', models.BooleanField(default=False, verbose_name='Спальное место')),
            ],
            options={
                'verbose_name': 'Диваны',
                'verbose_name_plural': 'Диваны',
            },
            bases=('icistore.product',),
        ),
        migrations.CreateModel(
            name='MainPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/', verbose_name='Видео')),
                ('videoImage', models.ImageField(blank=True, null=True, upload_to='videos/', verbose_name='Картинка Видео')),
                ('advantages', models.ManyToManyField(to='icistore.advantage', verbose_name='Преимущества')),
            ],
            options={
                'verbose_name': 'Видео для главной страницы',
                'verbose_name_plural': 'Видео для главной страницы',
            },
        ),
        migrations.AddField(
            model_name='category',
            name='filters',
            field=models.ManyToManyField(blank=True, to='icistore.filter'),
        ),
    ]
