# Generated by Django 4.2.6 on 2023-10-12 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Chair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('subtitle', models.CharField(max_length=200, verbose_name='Вид')),
                ('manufacturer', models.CharField(blank=True, max_length=100, verbose_name='Производитель')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='Страна')),
                ('delivery_days', models.IntegerField(default=0, verbose_name='Доставка в днях')),
                ('warranty', models.CharField(blank=True, max_length=100, verbose_name='гарантия')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликован')),
                ('is_top_product', models.BooleanField(default=False, verbose_name='Популярный')),
                ('price', models.IntegerField(blank=True, default=False, verbose_name='Цена')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icistore.category', verbose_name='Категория')),
            ],
        ),
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/')),
            ],
        ),
        migrations.CreateModel(
            name='InteriorSofa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('subtitle', models.CharField(max_length=200, verbose_name='Вид')),
                ('manufacturer', models.CharField(blank=True, max_length=100, verbose_name='Производитель')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='Страна')),
                ('delivery_days', models.IntegerField(default=0, verbose_name='Доставка в днях')),
                ('warranty', models.CharField(blank=True, max_length=100, verbose_name='гарантия')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликован')),
                ('is_top_product', models.BooleanField(default=False, verbose_name='Популярный')),
                ('price', models.IntegerField(blank=True, default=False, verbose_name='Цена')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icistore.category', verbose_name='Категория')),
                ('images', models.ManyToManyField(blank=True, to='icistore.imagemodel', verbose_name='Фото')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ottoman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('subtitle', models.CharField(max_length=200, verbose_name='Вид')),
                ('manufacturer', models.CharField(blank=True, max_length=100, verbose_name='Производитель')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='Страна')),
                ('delivery_days', models.IntegerField(default=0, verbose_name='Доставка в днях')),
                ('warranty', models.CharField(blank=True, max_length=100, verbose_name='гарантия')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликован')),
                ('is_top_product', models.BooleanField(default=False, verbose_name='Популярный')),
                ('price', models.IntegerField(blank=True, default=False, verbose_name='Цена')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icistore.category', verbose_name='Категория')),
                ('images', models.ManyToManyField(blank=True, to='icistore.imagemodel', verbose_name='Фото')),
                ('materials', models.ManyToManyField(blank=True, to='icistore.material', verbose_name='Материал ткани')),
            ],
        ),
        migrations.CreateModel(
            name='Sofa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('subtitle', models.CharField(max_length=200, verbose_name='Вид')),
                ('manufacturer', models.CharField(blank=True, max_length=100, verbose_name='Производитель')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='Страна')),
                ('delivery_days', models.IntegerField(default=0, verbose_name='Доставка в днях')),
                ('warranty', models.CharField(blank=True, max_length=100, verbose_name='гарантия')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликован')),
                ('is_top_product', models.BooleanField(default=False, verbose_name='Популярный')),
                ('price', models.IntegerField(blank=True, default=False, verbose_name='Цена')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icistore.category', verbose_name='Категория')),
                ('images', models.ManyToManyField(blank=True, to='icistore.imagemodel', verbose_name='Фото')),
                ('materials', models.ManyToManyField(blank=True, to='icistore.material', verbose_name='Материал ткани')),
            ],
        ),
        migrations.CreateModel(
            name='SofaFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form', models.CharField(choices=[('эркерный', 'Эркерный'), ('модульный', 'Модульный'), ('прямой', 'Прямой'), ('угловой', 'Угловой')], max_length=50, verbose_name='Форма')),
                ('size', models.CharField(choices=[('до 2000мм', 'До 2000мм'), ('2000-3000мм', '2000-3000мм'), ('свыше 3000мм', 'Свыше 3000мм')], max_length=50, verbose_name='Размер')),
                ('has_sleeper', models.BooleanField(default=False, verbose_name='Спальное место')),
                ('sofa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icistore.sofa')),
            ],
        ),
        migrations.CreateModel(
            name='OttomanFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form', models.CharField(choices=[('круглая', 'Круглая'), ('прямоугольная', 'Прямоугольная')], max_length=50, verbose_name='Форма')),
                ('legs', models.CharField(choices=[('металл', 'Металл'), ('бук', 'Бук')], max_length=50, verbose_name='Материал')),
                ('ottoman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icistore.ottoman')),
            ],
        ),
        migrations.CreateModel(
            name='InteriorSofaFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appearance', models.CharField(choices=[('с высокой спинкой', 'С высокой спинкой'), ('с невысокой спинкой', 'С невысокой спинкой')], max_length=50, verbose_name='Спинка')),
                ('legs', models.CharField(choices=[('металл', 'Металл'), ('бук', 'Бук')], max_length=50, verbose_name='Материал')),
                ('has_armrests', models.BooleanField(default=False, verbose_name='Спальное место')),
                ('interior_sofa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icistore.interiorsofa')),
            ],
        ),
        migrations.AddField(
            model_name='interiorsofa',
            name='materials',
            field=models.ManyToManyField(blank=True, to='icistore.material', verbose_name='Материал ткани'),
        ),
        migrations.CreateModel(
            name='ChairFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appearance', models.CharField(choices=[('с высокой спинкой', 'С высокой спинкой'), ('с невысокой спинкой', 'С невысокой спинкой')], max_length=50, verbose_name='Спинка')),
                ('form', models.CharField(choices=[('круглая', 'Круглая'), ('прямоугольная', 'Прямоугольная')], max_length=50, verbose_name='Форма')),
                ('legs', models.CharField(choices=[('металл', 'Металл'), ('бук', 'Бук')], max_length=50, verbose_name='Материал')),
                ('chair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='icistore.chair')),
            ],
        ),
        migrations.AddField(
            model_name='chair',
            name='images',
            field=models.ManyToManyField(blank=True, to='icistore.imagemodel', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='chair',
            name='materials',
            field=models.ManyToManyField(blank=True, to='icistore.material', verbose_name='Материал ткани'),
        ),
    ]
