# Generated by Django 4.2.6 on 2023-10-18 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('icistore', '0002_alter_type_options_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='subtitle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='icistore.type', verbose_name='Вид'),
        ),
    ]
