# Generated by Django 4.2.6 on 2023-10-12 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icistore', '0003_alter_imagemodel_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/')),
            ],
        ),
    ]
